/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "gold-100": "var(--gold-100)",
        "gold-200": "var(--gold-200)",
        "gold-300": "var(--gold-300)",
        "gold-400": "var(--gold-400)",
        "gold-50": "var(--gold-50)",
        "gold-500": "var(--gold-500)",
        "gold-600": "var(--gold-600)",
        "gold-700": "var(--gold-700)",
        "gold-800": "var(--gold-800)",
        "gold-900": "var(--gold-900)",
        "gold-950": "var(--gold-950)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-50": "var(--gray-50)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-800": "var(--gray-800)",
        "gray400-raw-color": "var(--gray400-raw-color)",
        "lime-100": "var(--lime-100)",
        "lime-200": "var(--lime-200)",
        "lime-300": "var(--lime-300)",
        "lime-400": "var(--lime-400)",
        "lime-50": "var(--lime-50)",
        "lime-500": "var(--lime-500)",
        "lime-600": "var(--lime-600)",
        "lime-700": "var(--lime-700)",
        "lime-800": "var(--lime-800)",
        "lime-900": "var(--lime-900)",
        "lime-950": "var(--lime-950)",
        "orange-100": "var(--orange-100)",
        "orange-200": "var(--orange-200)",
        "orange-300": "var(--orange-300)",
        "orange-400": "var(--orange-400)",
        "orange-50": "var(--orange-50)",
        "orange-500": "var(--orange-500)",
        "orange-600": "var(--orange-600)",
        "orange-700": "var(--orange-700)",
        "orange-800": "var(--orange-800)",
        "orange-900": "var(--orange-900)",
        "orange-950": "var(--orange-950)",
      },
      fontFamily: {
        "body-text-20": "var(--body-text-20-font-family)",
        "body-text-extra-small": "var(--body-text-extra-small-font-family)",
        "body-text-large": "var(--body-text-large-font-family)",
        "body-text-regular": "var(--body-text-regular-font-family)",
        "body-text-small": "var(--body-text-small-font-family)",
        "display-font-1-bold": "var(--display-font-1-bold-font-family)",
        "display-font-1-medium": "var(--display-font-1-medium-font-family)",
        "display-font-1-semi-bold":
          "var(--display-font-1-semi-bold-font-family)",
        "display-font-2-bold": "var(--display-font-2-bold-font-family)",
        "display-font-2-medium": "var(--display-font-2-medium-font-family)",
        "display-font-2-semi-bold":
          "var(--display-font-2-semi-bold-font-family)",
        "h1-bold": "var(--h1-bold-font-family)",
        "h1-medium": "var(--h1-medium-font-family)",
        "h1-semi-bold": "var(--h1-semi-bold-font-family)",
        "h2-bold": "var(--h2-bold-font-family)",
        "h2-medium": "var(--h2-medium-font-family)",
        "h2-semi-bold": "var(--h2-semi-bold-font-family)",
        "h3-bold": "var(--h3-bold-font-family)",
        "h3-medium": "var(--h3-medium-font-family)",
        "h3-semi-bold": "var(--h3-semi-bold-font-family)",
        "h4-bold": "var(--h4-bold-font-family)",
        "h4-medium": "var(--h4-medium-font-family)",
        "h4-semi-bold": "var(--h4-semi-bold-font-family)",
        "h5-bold": "var(--h5-bold-font-family)",
        "h5-medium": "var(--h5-medium-font-family)",
        "h5-semi-bold": "var(--h5-semi-bold-font-family)",
        "h6-bold": "var(--h6-bold-font-family)",
        "h6-medium": "var(--h6-medium-font-family)",
        "h6-semi-bold": "var(--h6-semi-bold-font-family)",
        h7: "var(--h7-font-family)",
      },
      boxShadow: {
        card: "var(--card)",
      },
    },
  },
  plugins: [],
};
